name: Publish images to Docker Hub

on: push

env:
  REGISTRY_IMAGE: pauldn/meilisearch

jobs:
  docker:
    runs-on: ubuntu-24.04

    permissions:
      id-token: write # This is needed to use Cosign in keyless mode
    steps:
      - uses: actions/checkout@v5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Inspect image
        run: |
          digest=$(docker buildx imagetools inspect --raw getmeili/meilisearch:prototype-v1.26.0.arm-native-docker-build-0 | jq -r '.manifests[0].digest')
          echo "DIGEST=${digest}" >> $GITHUB_ENV

      - name: Test
        run: |
          echo "${{ env.DIGEST }}"
